import type { Metadata } from "next";

import "@/components/react-aria/theme.scss";
import "@/components/react-aria/utilities.scss";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
